services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./dockerProd/db/data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.12
    restart: always
    volumes:
      - ./dockerProd/redis/data:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dockerProd/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - static_volume:/app/static
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - redis

    restart: always

volumes:
  static_volume:
